Repository frenck/spook, pull requests merged in 2023-03, with the labels that each got.

#22 Cleanup missing entity detection a little
  custom_components/spook/repairs/automation_unknown_entity_references.py
  custom_components/spook/repairs/script_unknown_entity_references.py
Labels: refactor

#23 Adds scripts to the specific entities counted.
  README.md
  custom_components/spook/sensor.py
Labels: new-feature

#26 Add input_number.shuffle & sort service
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/input_select_shuffle.py
  custom_components/spook/services/input_select_sort.py
Labels: new-feature

#27 Fix service description schema for number.increment & input_number.increment
  custom_components/spook/services.yaml
Labels: bugfix

#28 Let Home Assistant accept this as repair platform
  custom_components/spook/repairs/__init__.py
Labels: bugfix

#29 Add repairs: Unknown group members
  README.md
  custom_components/spook/repairs/group_unknown_members.py
  custom_components/spook/translations/en.json
Labels: new-feature

#31 Add more known removed YAML domains
  custom_components/spook/repairs/obsolete_integration_yaml_config.py
Labels: enhancement

#32 Add repair: Find known old platform configuration
  custom_components/spook/repairs/obsolete_platform_yaml_config.py
  custom_components/spook/translations/en.json
Labels: new-feature

#36 Remove unneeded return statement
  custom_components/spook/services/__init__.py
Labels: refactor

#45 Fix statistics_id -> statistic_id in service description
  custom_components/spook/services.yaml
Labels: bugfix

#47 Add repair: Find missing source in integration helpers
  README.md
  custom_components/spook/repairs/integration_unknown_source.py
  custom_components/spook/translations/en.json
Labels: new-feature

#48 Add service: Create area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_create_area.py
Labels: new-feature

#50 Rename remove area to delete area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_delete_area.py
Labels: refactor

#51 Rename remove all orphaned entities service to delete
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_delete_all_orphaned_entities.py
Labels: breaking-change

#52 Add service: Add device to area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_add_device_to_area.py
Labels: new-feature

#53 Add service: Remove device from area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_remove_device_from_area.py
Labels: new-feature

#54 Add service: Add entity to area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_add_entity_to_area.py
Labels: new-feature

#55 Add service: Remove entity to area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_remove_entity_from_area.py
Labels: new-feature

#56 Fix add device/entity to area
  custom_components/spook/services/homeassistant_add_device_to_area.py
  custom_components/spook/services/homeassistant_add_entity_to_area.py
Labels: bugfix

#57 Add service: Add alias to area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_add_alias_to_area.py
Labels: new-feature

#58 Add service: Remove alias from area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_remove_alias_from_area.py
Labels: new-feature

#59 Add service: Set aliases for an area
  README.md
  custom_components/spook/services.yaml
  custom_components/spook/services/homeassistant_set_area_aliases.py
Labels: new-feature

#64 Fix input number increment/decrement steps
  custom_components/spook/services/input_number_decrement.py
  custom_components/spook/services/input_number_increment.py
Labels: bugfix

#63 Adds translations for `pt-BR`
  custom_components/spook/translations/pt-BR.json
Labels: enhancement

#66 Add french translations
  custom_components/spook/translations/fr.json
Labels: enhancement

#69 Ignore persistent_notification entities when detecting unused entities
  custom_components/spook/repairs/automation_unknown_entity_references.py
  custom_components/spook/repairs/script_unknown_entity_references.py
Labels: bugfix

#70 Ignore Templates when detecting unused entities
  custom_components/spook/repairs/automation_unknown_entity_references.py
  custom_components/spook/repairs/script_unknown_entity_references.py
Labels: bugfix

#73 Add Italian translations
  custom_components/spook/translations/it.json
Labels: enhancement

#76 Fix statistics import service to accept None for last_rest
  custom_components/spook/services/recorder_import_statistics.py
Labels: bugfix

#80 Add SonarCloud badge & Renovate
  .github/dependabot.yml
  README.md
  renovate.json
  sonar-project.properties
Labels: maintenance

#92 Collection of development/ci env tweaks
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/LICENSE.md
  .github/SECURITY.md
  .github/renovate.json
  .github/workflows/black.yaml
  .github/workflows/hacs.yaml
  .github/workflows/hassfest.yaml
  .github/workflows/labels.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/pylint.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/release.yaml
  .github/workflows/ruff.yaml
Labels: maintenance

#97 Small adjustment to CI & Renovate config
  .github/renovate.json
  .github/workflows/pr-labels.yaml
Labels: ci

#96 Add German translation
  custom_components/spook/translations/de.json
Labels: enhancement

#100 Use async_set_value function instead
  custom_components/spook/services/input_number_decrement.py
  custom_components/spook/services/input_number_increment.py
  custom_components/spook/services/input_number_max.py
  custom_components/spook/services/input_number_min.py
  custom_components/spook/services/number_decrement.py
  custom_components/spook/services/number_increment.py
Labels: bugfix

#106 Add aladdin_connect and scrape as known obsolete YAML
  custom_components/spook/repairs/obsolete_platform_yaml_config.py
Labels: enhancement
