Repository frenck/spook, pull requests merged in 2023-10, with the labels that each got.

#380 Don't use LOGGER.error for debug logging during scene entities check
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
Labels: bugfix

#422 Replace black with ruff
  .github/workflows/black.yaml
  .github/workflows/ruff.yaml
  .pre-commit-config.yaml
  custom_components/spook/config_flow.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  poetry.lock
  pyproject.toml
Labels: ci

#426 Add Home Assistant restart safe_mode support
  custom_components/spook/ectoplasms/homeassistant/services/restart.py
  custom_components/spook/services.yaml
Labels: bugfix

#427 Fix no attribute EVENT_PERSISTENT_NOTIFICATIONS_UPDATED
  custom_components/spook/ectoplasms/homeassistant/sensor.py
Labels: bugfix

#424 Fixed typo in automation integration documentation
  documentation/integrations/automation.md
  documentation/integrations/script.md
Labels: documentation

#428 Translations update from Hosted Weblate
  custom_components/spook/translations/it.json
Labels: maintenance

#433 Translations update from Hosted Weblate
  custom_components/spook/translations/it.json
Labels: maintenance
