Repository frenck/spook, pull requests merged in 2023-04, with the labels that each got.

#117 Correction to German translation
  custom_components/spook/translations/de.json
Labels: enhancement

#114 Fix subtract instead of add
  custom_components/spook/services/input_number_decrement.py
  custom_components/spook/services/number_decrement.py
Labels: bugfix

#124 Add repair: Find missing source switches for switch_as_x helpers
  custom_components/spook/repairs/switch_as_x_unknown_source.py
  custom_components/spook/translations/en.json
Labels: new-feature

#125 Add docs for switch_as_x repair
  README.md
Labels: documentation

#126 Bump min required Home Assistant to 2023.4.0
  hacs.json
Labels: maintenance

#127 Update translations for pt-BR after #124
  custom_components/spook/translations/pt-BR.json
Labels: enhancement
