Repository frenck/spook, pull requests merged in 2023-12, with the labels that each got.

#459 Fix typo for `Boo!` service
  custom_components/spook/services.yaml
Labels: enhancement

#472 Fix accepting list of devices in enable/disable service
  custom_components/spook/ectoplasms/homeassistant/services/disable_device.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_device.py
Labels: bugfix

#473 Allow enabling/disable multiple config entries in a single call
  custom_components/spook/ectoplasms/homeassistant/services/disable_config_entry.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_config_entry.py
  documentation/integrations.md
Labels: new-feature

#497 Fix crash on unavailable automations & scripts
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
Labels: bugfix

#499 Skip device IDs that are empty strings
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
Labels: bugfix

#500 Skip scene inspection is data platform is missing
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
Labels: bugfix

#501 Translations update from Hosted Weblate
  custom_components/spook/translations/nl.json
Labels: maintenance

#504 Add Spook's mention in the Self-Hosted podcast
  documentation/media.md
Labels: documentation

#505 Add video about Spook from Gryd
  documentation/media.md
Labels: documentation

#506 Fix embedded video in the docs
  documentation/media.md
Labels: documentation

#502 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/ur.json
Labels: maintenance

#503 Translations update from Hosted Weblate
  custom_components/spook/translations/ur.json
Labels: maintenance

#507 Add support for forwarding entry setup to Ectoplasms
  custom_components/spook/__init__.py
  custom_components/spook/util.py
Labels: new-feature

#510 Bump min required Home Assistant to 2023.12.0
  documentation/installation.md
  hacs.json
Labels: breaking-change

#512 Add possibility to extend the Home Assistant template engine
  custom_components/spook/__init__.py
  custom_components/spook/templating.py
  custom_components/spook/util.py
Labels: new-feature

#514 Add template method: shuffle
  custom_components/spook/ectoplasms/homeassistant/templating/__init__.py
  custom_components/spook/ectoplasms/homeassistant/templating/shuffle.py
Labels: new-feature
