Repository frenck/spook, pull requests merged in 2023-08, with the labels that each got.

#263 Add CC0 license on the translations provided by Spook
  README.md
  custom_components/spook/translations/LICENSE.md
Labels: maintenance

#241 Translations update from Hosted Weblate
  custom_components/spook/translations/bg.json
  custom_components/spook/translations/ca.json
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/da.json
  custom_components/spook/translations/de.json
  custom_components/spook/translations/el.json
  custom_components/spook/translations/es.json
  custom_components/spook/translations/et.json
  custom_components/spook/translations/he.json
  custom_components/spook/translations/hu.json
  custom_components/spook/translations/id.json
  custom_components/spook/translations/ja.json
  custom_components/spook/translations/ka.json
  custom_components/spook/translations/ko.json
  custom_components/spook/translations/lb.json
  custom_components/spook/translations/lv.json
  custom_components/spook/translations/nb_NO.json
  custom_components/spook/translations/nl.json
  custom_components/spook/translations/pt.json
  custom_components/spook/translations/ro.json
  custom_components/spook/translations/ru.json
  custom_components/spook/translations/sk.json
  custom_components/spook/translations/sl.json
  custom_components/spook/translations/sv.json
  custom_components/spook/translations/th.json
  custom_components/spook/translations/tr.json
  custom_components/spook/translations/uk.json
  custom_components/spook/translations/zh_Hans.json
  custom_components/spook/translations/zh_Hant.json
Labels: maintenance

#264 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/nb_NO.json
  custom_components/spook/translations/sv.json
Labels: maintenance

#266 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/da.json
  custom_components/spook/translations/sv.json
Labels: maintenance

#269 Bump Home Assistant to 2023.8.1 (set minimum to 2023.8.0)
  .github/workflows/black.yaml
  .github/workflows/pylint.yaml
  .github/workflows/ruff.yaml
  hacs.json
  poetry.lock
  pyproject.toml
  sonar-project.properties
Labels: maintenance, dependencies

#271 Sign Spook release package
  .github/workflows/release.yaml
Labels: ci

#272 Put back translations into the README
  README.md
Labels: documentation

#273 Add issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#275 Improvements to the issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: maintenance

#276 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#277 Fix typo
  documentation/background_and_history.md
Labels: documentation

#278 Fix missing space
  documentation/installation.md
Labels: documentation

#279 Add devcontainer
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
Labels: maintenance

#280 Fix typo
  documentation/integrations/cloud.md
Labels: documentation

#281 Add social description to index
  documentation/index.md
Labels: documentation

#282 Fix minimal Home Assistant version in docs
  documentation/installation.md
Labels: documentation

#283 Small tweaks to installation procedure
  documentation/installation.md
  documentation/myst.yml
Labels: documentation

#284 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/it.json
Labels: maintenance

#288 Typo "Uhnide" -> "Unhide"
  documentation/services.md
Labels: documentation

#285 Collection of documentation improvements
  README.md
  documentation/areas.md
  documentation/devices.md
  documentation/features.md
  documentation/installation.md
  documentation/integrations.md
  documentation/myst.yml
Labels: documentation

#289 Don't upload sigstore signatures
  .github/workflows/release.yaml
Labels: ci, bugfix

#291 Update all sub-dependencies
  poetry.lock
Labels: maintenance

#292 Use the same isort/ruff import sorting as HA
  custom_components/spook/config_flow.py
  custom_components/spook/ectoplasms/blueprint/services/importer.py
  custom_components/spook/ectoplasms/cloud/switch.py
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/ectoplasms/homeassistant/services/add_alias_to_area.py
  custom_components/spook/ectoplasms/homeassistant/services/add_device_to_area.py
  custom_components/spook/ectoplasms/homeassistant/services/add_entity_to_area.py
  custom_components/spook/ectoplasms/homeassistant/services/create_area.py
  custom_components/spook/ectoplasms/homeassistant/services/delete_area.py
  custom_components/spook/ectoplasms/homeassistant/services/disable_config_entry.py
  custom_components/spook/ectoplasms/homeassistant/services/disable_device.py
  custom_components/spook/ectoplasms/homeassistant/services/disable_entity.py
  custom_components/spook/ectoplasms/homeassistant/services/disable_polling.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_config_entry.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_device.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_entity.py
  custom_components/spook/ectoplasms/homeassistant/services/enable_polling.py
  custom_components/spook/ectoplasms/homeassistant/services/hide_entity.py
  custom_components/spook/ectoplasms/homeassistant/services/ignore_all_discovered.py
  custom_components/spook/ectoplasms/homeassistant/services/remove_alias_from_area.py
  custom_components/spook/ectoplasms/homeassistant/services/remove_device_from_area.py
  custom_components/spook/ectoplasms/homeassistant/services/remove_entity_from_area.py
  custom_components/spook/ectoplasms/homeassistant/services/restart.py
  custom_components/spook/ectoplasms/homeassistant/services/set_area_aliases.py
  custom_components/spook/ectoplasms/homeassistant/services/unhide_entity.py
  custom_components/spook/ectoplasms/input_number/services/decrement.py
  custom_components/spook/ectoplasms/input_number/services/increment.py
  custom_components/spook/ectoplasms/number/services/decrement.py
  custom_components/spook/ectoplasms/number/services/increment.py
  custom_components/spook/ectoplasms/recorder/services/import_statistics.py
  custom_components/spook/ectoplasms/repairs/services/create.py
  custom_components/spook/ectoplasms/repairs/services/remove.py
  custom_components/spook/ectoplasms/select/services/random.py
  custom_components/spook/repairs.py
  custom_components/spook/services.py
  pyproject.toml
Labels: maintenance

#293 Add support for event entities in ectoplasms
  custom_components/spook/event.py
Labels: enhancement

#295 Add support for service responses
  custom_components/spook/services.py
Labels: enhancement

#297 Add repairs issue sensors
  custom_components/spook/ectoplasms/repairs/entity.py
  custom_components/spook/ectoplasms/repairs/sensor.py
  custom_components/spook/translations/en.json
Labels: new-feature

#300 Add event entity for Home Assistant Repairs
  custom_components/spook/const.py
  custom_components/spook/ectoplasms/repairs/event.py
  custom_components/spook/translations/en.json
Labels: new-feature

#302 Add button entities for ignoring / unignoring repairs
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/translations/en.json
Labels: new-feature

#303 Fix import location of EntityCategory
  custom_components/spook/ectoplasms/cloud/switch.py
  custom_components/spook/ectoplasms/homeassistant/button.py
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/ectoplasms/repairs/sensor.py
Labels: enhancement

#304 Add services to add/update/delete zones
  custom_components/spook/ectoplasms/zone/__init__.py
  custom_components/spook/ectoplasms/zone/services/__init__.py
  custom_components/spook/ectoplasms/zone/services/create.py
  custom_components/spook/ectoplasms/zone/services/delete.py
  custom_components/spook/ectoplasms/zone/services/update.py
  custom_components/spook/manifest.json
  custom_components/spook/services.yaml
Labels: new-feature

#299 Translations update from Hosted Weblate
  custom_components/spook/translations/de.json
  custom_components/spook/translations/es.json
  custom_components/spook/translations/nl.json
Labels: maintenance

#305 Document new zone features
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/images/integrations/zone/create.png
  documentation/images/integrations/zone/delete.png
  documentation/images/integrations/zone/example.png
  documentation/images/integrations/zone/update.png
  documentation/integrations/zone.md
Labels: documentation

#306 Document new Home Assistant Repairs device & entities
  documentation/images/integrations/repairs/devices_entities.png
  documentation/integrations/repairs.md
Labels: documentation

#307 Be a big boy, switch to SemVer
  README.md
  documentation/faq.md
Labels: documentation

#315 Update support pages to correct discussion URLs
  documentation/support.md
Labels: documentation

#320 Fix zone services not working with YAML home zone
  custom_components/spook/ectoplasms/zone/services/create.py
  custom_components/spook/ectoplasms/zone/services/delete.py
  custom_components/spook/ectoplasms/zone/services/update.py
Labels: bugfix

#321 Fix unknown dashboard entities repair for filtered badges
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
Labels: bugfix

#322 Fix implicit use of device name in Repairs event
  custom_components/spook/ectoplasms/repairs/event.py
Labels: bugfix

#319 Translations update from Hosted Weblate
  custom_components/spook/translations/uk.json
Labels: maintenance

#323 Add support for sub-integrations
  custom_components/spook/__init__.py
  custom_components/spook/config_flow.py
  custom_components/spook/integrations/__init__.py
  custom_components/spook/repairs.py
  custom_components/spook/translations/en.json
  custom_components/spook/util.py
Labels: new-feature

#329 Fix unknown entity references for badge objects in dashboards
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
Labels: bugfix

#330 Add inverse entity helper
  .github/workflows/release.yaml
  custom_components/spook/integrations/spook_inverse/__init__.py
  custom_components/spook/integrations/spook_inverse/binary_sensor.py
  custom_components/spook/integrations/spook_inverse/config_flow.py
  custom_components/spook/integrations/spook_inverse/const.py
  custom_components/spook/integrations/spook_inverse/cover.py
  custom_components/spook/integrations/spook_inverse/entity.py
  custom_components/spook/integrations/spook_inverse/manifest.json
  custom_components/spook/integrations/spook_inverse/switch.py
  custom_components/spook/integrations/spook_inverse/translations/en.json
  custom_components/spook/util.py
Labels: new-feature

#331 Add services to add/remove device trackers from persons
  custom_components/spook/ectoplasms/person/__init__.py
  custom_components/spook/ectoplasms/person/services/__init__.py
  custom_components/spook/ectoplasms/person/services/add_device_tracker.py
  custom_components/spook/ectoplasms/person/services/remove_device_tracker.py
  custom_components/spook/manifest.json
  custom_components/spook/services.yaml
Labels: new-feature
