Repository frenck/spook, pull requests merged in 2023-09, with the labels that each got.

#333 Translations update from Hosted Weblate
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/pt.json
  custom_components/spook/translations/uk.json
Labels: maintenance

#351 Translations update from Hosted Weblate
  custom_components/spook/translations/nb_NO.json
Labels: maintenance

#358 Remove cover support from inverse for now
  custom_components/spook/integrations/spook_inverse/config_flow.py
  custom_components/spook/integrations/spook_inverse/const.py
  custom_components/spook/integrations/spook_inverse/cover.py
  custom_components/spook/integrations/spook_inverse/translations/en.json
Labels: enhancement

#359 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/de.json
  custom_components/spook/integrations/spook_inverse/translations/nl.json
Labels: maintenance

#360 Fix display of inverse helper
  custom_components/spook/integrations/spook_inverse/translations/en.json
Labels: bugfix

#361 Fix documentation site title
  documentation/myst.yml
Labels: documentation

#363 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/de.json
  custom_components/spook/integrations/spook_inverse/translations/nl.json
Labels: maintenance

#362 Documentation updates for v1.2.0
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/helpers.md
  documentation/helpers/inverse.md
  documentation/images/helpers/inverse/configure.png
  documentation/images/helpers/inverse/done.png
  documentation/images/helpers/inverse/helper_dialog.png
  documentation/images/helpers/inverse/select_entity_type.png
  documentation/images/integrations/person/add_device_tracker.png
  documentation/images/integrations/person/example.png
  documentation/images/integrations/person/remove_device_tracker.png
  documentation/integrations/person.md
  documentation/support.md
Labels: documentation

#366 Raise repairs for unknown entity references in scenes
  custom_components/spook/ectoplasms/scene/__init__.py
  custom_components/spook/ectoplasms/scene/repairs/__init__.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/translations/en.json
Labels: new-feature

#372 Reduce repair event debounce cooldown period to 3 seconds
  custom_components/spook/repairs.py
Labels: enhancement

#373 Add helpers to features documentation
  documentation/features.md
Labels: documentation

#374 Add person services to service index
  documentation/services.md
Labels: documentation

#375 Add documentation for scene repair inspections
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/images/integrations/scene/unknown_entity.png
  documentation/integrations/scene.md
Labels: documentation
