Repository frenck/spook, pull requests merged in 2023-05, with the labels that each got.

#162 Prevent repair inspections to run during shutdown
  custom_components/spook/repairs/__init__.py
Labels: bugfix

#163 Don't inspect group repairs if integration isn't loaded
  custom_components/spook/repairs/group_unknown_members.py
Labels: bugfix

#165 Add samsungtv as known obsolete YAML config
  custom_components/spook/repairs/obsolete_integration_yaml_config.py
Labels: enhancement

#170 Add repair: Find unknown entities on dashboards
  custom_components/spook/manifest.json
  custom_components/spook/repairs/lovelace_unknown_entity_references.py
  custom_components/spook/translations/en.json
Labels: new-feature

#172 Add rainbird as knonwn obsolete YAML config
  custom_components/spook/repairs/obsolete_integration_yaml_config.py
Labels: enhancement

#171 Add skybell as known obsolete YAML config
  custom_components/spook/repairs/obsolete_integration_yaml_config.py
Labels: enhancement

#174 Update french translations
  custom_components/spook/translations/fr.json
Labels: enhancement

#175 Fix repairs of default dashboard
  custom_components/spook/repairs/lovelace_unknown_entity_references.py
Labels: bugfix

#176 Repairs: Ignore invalid entity IDs in all cases
  custom_components/spook/repairs/automation_unknown_entity_references.py
  custom_components/spook/repairs/group_unknown_members.py
  custom_components/spook/repairs/lovelace_unknown_entity_references.py
  custom_components/spook/repairs/script_unknown_entity_references.py
Labels: bugfix

#177 Update German translation
  custom_components/spook/translations/de.json
Labels: enhancement
