Repository frenck/spook, pull requests merged in 2024-08, with the labels that each got.

#804 Remove platinum quality scale markers (they where fake anyways)
  custom_components/spook/integrations/spook_inverse/manifest.json
  custom_components/spook/manifest.json
Labels: bugfix

#798 Search for unknown entities inside sections
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
Labels: enhancement

#747 Translations update from Hosted Weblate
  custom_components/spook/translations/da.json
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/it.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/ru.json
  custom_components/spook/translations/sk.json
  custom_components/spook/translations/tr.json
Labels: maintenance

#761 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/ru.json
Labels: maintenance

#752 Add list_orphaned_database_entities service
  custom_components/spook/ectoplasms/homeassistant/services/list_orphaned_database_entities.py
  custom_components/spook/services.yaml
  documentation/core_extensions.md
  documentation/entities.md
  documentation/images/entities/list_orphaned_database_entities.png
Labels: new-feature

#805 Rename 'service' to 'action' following Home Assistant 2024.8
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/services.yaml
  custom_components/spook/translations/de.json
  custom_components/spook/translations/en.json
  custom_components/spook/translations/es.json
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/nl.json
  custom_components/spook/util.py
  documentation/_toc.yml
  documentation/about.md
  documentation/actions.md
  documentation/areas.md
  documentation/background_and_history.md
  documentation/core_extensions.md
  documentation/devices.md
  documentation/devices_entities.md
  documentation/entities.md
  documentation/faq.md
  documentation/features.md
  documentation/floors.md
  documentation/glossary.md
  documentation/helpers/inverse.md
  documentation/integrations.md
  documentation/integrations/_template.md
  documentation/integrations/automation.md
  documentation/integrations/blueprint.md
  documentation/integrations/cloud.md
  documentation/integrations/group.md
  documentation/integrations/input_number.md
  documentation/integrations/input_select.md
  documentation/integrations/integration.md
  documentation/integrations/lovelace.md
  documentation/integrations/number.md
  documentation/integrations/person.md
  documentation/integrations/proximity.md
  documentation/integrations/recorder.md
  documentation/integrations/repairs.md
  documentation/integrations/scene.md
  documentation/integrations/script.md
  documentation/integrations/select.md
  documentation/integrations/switch_as_x.md
  documentation/integrations/timer.md
  documentation/integrations/trend.md
  documentation/integrations/utility_meter.md
  documentation/integrations/zone.md
  documentation/labels.md
  documentation/misc.md
  documentation/other_features.md
  documentation/services.md
  documentation/template_functions.md
  documentation/usage.md
Labels: documentation, minor, maintenance

#807 Translations update from Hosted Weblate
  custom_components/spook/translations/ru.json
Labels: maintenance
