Repository frenck/spook, pull requests merged in 2024-02, with the labels that each got.

#584 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/tr.json
Labels: maintenance

#583 Translations update from Hosted Weblate
  custom_components/spook/translations/de.json
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/tr.json
Labels: maintenance

#593 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/pt.json
  custom_components/spook/integrations/spook_inverse/translations/pt_BR.json
Labels: maintenance

#592 Translations update from Hosted Weblate
  custom_components/spook/translations/it.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/pt.json
Labels: maintenance

#595 Bump min req Home Assistant 2024.2.0 and HACS 1.34.0
  hacs.json
Labels: maintenance

#600 Add inspections for unknown service calls in automations
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/translations/en.json
  documentation/integrations/automation.md
Labels: new-feature

#599 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/cs.json
Labels: maintenance

#598 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/da.json
Labels: maintenance

#596 Add inspections for proximity issues
  custom_components/spook/ectoplasms/proximity/__init__.py
  custom_components/spook/ectoplasms/proximity/repairs/__init__.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py
  custom_components/spook/manifest.json
  custom_components/spook/translations/en.json
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/glossary.md
  documentation/installation.md
  documentation/integrations/proximity.md
Labels: new-feature

#601 Translations update from Hosted Weblate
  custom_components/spook/translations/de.json
  custom_components/spook/translations/es.json
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/it.json
  custom_components/spook/translations/nb_NO.json
  custom_components/spook/translations/nl.json
Labels: maintenance

#602 Fix rendering of proximity documentation page
  documentation/integrations/proximity.md
Labels: documentation

#603 Deduplicate repair issue cleanup code
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
  custom_components/spook/ectoplasms/trend/repairs/unknown_source.py
  custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py
  custom_components/spook/repairs.py
Labels: refactor

#606 Refactor getting/filtering for unknown entity/area/devices/services
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_zone.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
  custom_components/spook/ectoplasms/trend/repairs/unknown_source.py
  custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py
  custom_components/spook/util.py
Labels: refactor

#607 Fix parsing of used services when encountering a repeat action
  custom_components/spook/util.py
Labels: bugfix

#611 Translations update from Hosted Weblate
  custom_components/spook/translations/da.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/ru.json
  custom_components/spook/translations/sk.json
Labels: maintenance

#605 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/da.json
  custom_components/spook/integrations/spook_inverse/translations/it.json
Labels: maintenance

#617 Fix detecting service calls that use old-style service_template
  custom_components/spook/util.py
Labels: bugfix
