Repository frenck/spook, pull requests merged in 2024-01, with the labels that each got.

#521 Add template method: fnmatch_filter
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch_filter.py
Labels: new-feature

#520 Add template method: fnmatch
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch.py
Labels: new-feature

#522 Add template method: typeof
  custom_components/spook/ectoplasms/homeassistant/templating/typeof.py
Labels: new-feature

#508 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/bg.json
  custom_components/spook/integrations/spook_inverse/translations/ca.json
  custom_components/spook/integrations/spook_inverse/translations/cs.json
  custom_components/spook/integrations/spook_inverse/translations/da.json
  custom_components/spook/integrations/spook_inverse/translations/el.json
  custom_components/spook/integrations/spook_inverse/translations/es.json
  custom_components/spook/integrations/spook_inverse/translations/et.json
  custom_components/spook/integrations/spook_inverse/translations/fr.json
  custom_components/spook/integrations/spook_inverse/translations/gl.json
  custom_components/spook/integrations/spook_inverse/translations/he.json
  custom_components/spook/integrations/spook_inverse/translations/hu.json
  custom_components/spook/integrations/spook_inverse/translations/id.json
  custom_components/spook/integrations/spook_inverse/translations/it.json
  custom_components/spook/integrations/spook_inverse/translations/ja.json
  custom_components/spook/integrations/spook_inverse/translations/ka.json
  custom_components/spook/integrations/spook_inverse/translations/ko.json
  custom_components/spook/integrations/spook_inverse/translations/lb.json
  custom_components/spook/integrations/spook_inverse/translations/lv.json
  custom_components/spook/integrations/spook_inverse/translations/pt.json
  custom_components/spook/integrations/spook_inverse/translations/pt_BR.json
  custom_components/spook/integrations/spook_inverse/translations/ro.json
  custom_components/spook/integrations/spook_inverse/translations/ru.json
  custom_components/spook/integrations/spook_inverse/translations/sk.json
  custom_components/spook/integrations/spook_inverse/translations/sl.json
  custom_components/spook/integrations/spook_inverse/translations/sv.json
  custom_components/spook/integrations/spook_inverse/translations/th.json
  custom_components/spook/integrations/spook_inverse/translations/tr.json
  custom_components/spook/integrations/spook_inverse/translations/uk.json
  custom_components/spook/integrations/spook_inverse/translations/zh_Hans.json
  custom_components/spook/integrations/spook_inverse/translations/zh_Hant.json
Labels: maintenance

#529 Adjust supported Python version range
  poetry.lock
  pyproject.toml
Labels: maintenance

#530 :fireworks: Updates maintenance/license year to 2024
  .github/LICENSE.md
  README.md
  documentation/license.md
Labels: maintenance

#536 Modernize sensor entity descriptions
  custom_components/spook/ectoplasms/cloud/switch.py
  custom_components/spook/ectoplasms/homeassistant/button.py
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/ectoplasms/repairs/sensor.py
Labels: enhancement

#539 Fix detecting changes to groups
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
Labels: bugfix

#541 Do not freeze entity descriptions for backward-compatibility
  custom_components/spook/ectoplasms/cloud/switch.py
  custom_components/spook/ectoplasms/homeassistant/button.py
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/ectoplasms/repairs/sensor.py
Labels: bugfix

#542 Add option to listen for config entry changes to trigger repair
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
  custom_components/spook/repairs.py
Labels: refactor

#543 Refactor/improve listening for reload events on repairs
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
  custom_components/spook/repairs.py
Labels: refactor

#544 Clean up repairs created for no longer existing entities
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/switch_as_x/repairs/unknown_source.py
Labels: bugfix

#545 Add template method: md5
  custom_components/spook/ectoplasms/homeassistant/templating/md5.py
Labels: new-feature

#546 Add template method: sha1
  custom_components/spook/ectoplasms/homeassistant/templating/sha1.py
Labels: new-feature

#547 Add template method: sha256
  custom_components/spook/ectoplasms/homeassistant/templating/sha256.py
Labels: new-feature

#548 Add template method: sha512
  custom_components/spook/ectoplasms/homeassistant/templating/sha512.py
Labels: new-feature

#549 Allow template method to be named different for tests and filters
  custom_components/spook/templating.py
Labels: enhancement

#551 Add template method: flatten
  custom_components/spook/ectoplasms/homeassistant/templating/flatten.py
Labels: new-feature

#535 Translations update from Hosted Weblate
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/sk.json
Labels: maintenance

#532 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/ar.json
  custom_components/spook/integrations/spook_inverse/translations/da.json
  custom_components/spook/integrations/spook_inverse/translations/el.json
  custom_components/spook/integrations/spook_inverse/translations/fr.json
  custom_components/spook/integrations/spook_inverse/translations/nb_NO.json
  custom_components/spook/integrations/spook_inverse/translations/pl.json
  custom_components/spook/integrations/spook_inverse/translations/sk.json
Labels: maintenance

#515 Update Spook documentation for 2.0.0
  documentation/_toc.yml
  documentation/about.md
  documentation/areas.md
  documentation/core_extensions.md
  documentation/devices.md
  documentation/entities.md
  documentation/glossary.md
  documentation/integrations.md
  documentation/integrations/blueprint.md
  documentation/integrations/input_number.md
  documentation/integrations/input_select.md
  documentation/integrations/number.md
  documentation/integrations/person.md
  documentation/integrations/recorder.md
  documentation/integrations/repairs.md
  documentation/integrations/select.md
  documentation/integrations/timer.md
  documentation/integrations/zone.md
  documentation/misc.md
  documentation/myst.yml
  documentation/other_features.md
  documentation/services.md
  documentation/template_engine.md
  documentation/template_functions.md
  documentation/template_functions/flatten.md
  documentation/template_functions/fnmatch.md
  documentation/template_functions/fnmatch_filter.md
  documentation/template_functions/md5.md
  documentation/template_functions/sha1.md
  documentation/template_functions/sha256.md
  documentation/template_functions/sha512.md
  documentation/template_functions/shuffle.md
  documentation/template_functions/typeof.md
Labels: documentation

#537 Added service to update an entity's ID
  custom_components/spook/ectoplasms/homeassistant/services/update_entity_id.py
  custom_components/spook/services.yaml
  documentation/entities.md
  documentation/images/entities/update_entity_id.png
  documentation/services.md
Labels: new-feature

#557 Process documentation review comments
  documentation/areas.md
  documentation/devices.md
  documentation/devices_entities.md
  documentation/entities.md
  documentation/integrations.md
  documentation/integrations/_template.md
  documentation/integrations/automation.md
  documentation/integrations/blueprint.md
  documentation/integrations/cloud.md
  documentation/integrations/group.md
  documentation/integrations/input_number.md
  documentation/integrations/input_select.md
  documentation/integrations/integration.md
  documentation/integrations/lovelace.md
  documentation/integrations/number.md
  documentation/integrations/person.md
  documentation/integrations/recorder.md
  documentation/integrations/repairs.md
  documentation/integrations/scene.md
  documentation/integrations/script.md
  documentation/integrations/select.md
  documentation/integrations/switch_as_x.md
  documentation/integrations/timer.md
  documentation/integrations/zone.md
  documentation/misc.md
  documentation/template_engine.md
  documentation/template_functions.md
  documentation/template_functions/flatten.md
  documentation/template_functions/fnmatch.md
  documentation/template_functions/fnmatch_filter.md
  documentation/template_functions/md5.md
  documentation/template_functions/sha1.md
  documentation/template_functions/sha256.md
  documentation/template_functions/sha512.md
  documentation/template_functions/shuffle.md
  documentation/template_functions/typeof.md
Labels: documentation

#558 Detect unknown source used in utility meter helpers
  custom_components/spook/ectoplasms/utility_meter/__init__.py
  custom_components/spook/ectoplasms/utility_meter/repairs/__init__.py
  custom_components/spook/ectoplasms/utility_meter/repairs/unknown_source.py
  custom_components/spook/translations/en.json
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/integrations/utility_meter.md
Labels: new-feature

#560 Detect unknown source used in trend helpers
  custom_components/spook/ectoplasms/trend/__init__.py
  custom_components/spook/ectoplasms/trend/repairs/__init__.py
  custom_components/spook/ectoplasms/trend/repairs/unknown_source.py
  custom_components/spook/translations/en.json
  documentation/_toc.yml
  documentation/enhanced_integrations.md
  documentation/integrations/trend.md
Labels: new-feature

#567 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/pt_BR.json
Labels: maintenance

#566 Translations update from Hosted Weblate
  custom_components/spook/translations/ar.json
  custom_components/spook/translations/bg.json
  custom_components/spook/translations/ca.json
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/da.json
  custom_components/spook/translations/el.json
  custom_components/spook/translations/et.json
  custom_components/spook/translations/he.json
  custom_components/spook/translations/id.json
  custom_components/spook/translations/it.json
  custom_components/spook/translations/ja.json
  custom_components/spook/translations/ka.json
  custom_components/spook/translations/ko.json
  custom_components/spook/translations/lb.json
  custom_components/spook/translations/lv.json
  custom_components/spook/translations/nb_NO.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/pt-BR.json
  custom_components/spook/translations/pt.json
  custom_components/spook/translations/ro.json
  custom_components/spook/translations/ru.json
  custom_components/spook/translations/sl.json
  custom_components/spook/translations/sv.json
  custom_components/spook/translations/th.json
  custom_components/spook/translations/tr.json
  custom_components/spook/translations/zh_Hans.json
  custom_components/spook/translations/zh_Hant.json
Labels: maintenance

#568 Ensure timer is set up before adding services
  custom_components/spook/manifest.json
Labels: bugfix
