Repository frenck/spook, pull requests merged in 2024-03, with the labels that each got.

#647 Make cloud switch entity `_update_state` function a coro
  custom_components/spook/ectoplasms/cloud/switch.py
Labels: bugfix

#666 Fix for event filter
  custom_components/spook/repairs.py
Labels: bugfix

#614 Translations update from Hosted Weblate
  custom_components/spook/translations/da.json
  custom_components/spook/translations/gl.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/pt-BR.json
  custom_components/spook/translations/sk.json
  custom_components/spook/translations/sv.json
Labels: maintenance

#616 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/da.json
  custom_components/spook/integrations/spook_inverse/translations/sv.json
Labels: maintenance

#667 Fix auto-cleanup of repair issues
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/ectoplasms/integration/repairs/unknown_source.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
  custom_components/spook/repairs.py
Labels: bugfix

#669 Fix detecting empty device IDs
  custom_components/spook/util.py
Labels: bugfix

#672 Switch Spook to MIT license
  .github/CONTRIBUTING.md
  .github/LICENSE.md
  README.md
  documentation/about.md
  documentation/faq.md
  documentation/license.md
  pyproject.toml
Labels: major, maintenance

#679 Performance improvements
  custom_components/spook/ectoplasms/automation/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_device_references.py
  custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py
  custom_components/spook/ectoplasms/group/repairs/unknown_members.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_ignored_zones.py
  custom_components/spook/ectoplasms/proximity/repairs/unknown_tracked_entities.py
  custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_area_references.py
  custom_components/spook/ectoplasms/script/repairs/unknown_device_references.py
Labels: enhancement

#675 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
Labels: maintenance

#676 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/cs.json
Labels: maintenance

#671 v3.0.0
  .github/CONTRIBUTING.md
  .github/LICENSE.md
  README.md
  documentation/about.md
  documentation/faq.md
  documentation/license.md
  pyproject.toml
Labels: new-feature, refactor, major

#689 Add mentions of Spook in media
  documentation/media.md
Labels: documentation

#690 Some more doc tweaks
  documentation/index.md
Labels: documentation

#673 Migrate from Poetry to rye
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/pylint.yaml
  .github/workflows/ruff.yaml
  .gitignore
  .pre-commit-config.yaml
  .python-version
  .vscode/launch.json
  custom_components/spook/ectoplasms/blueprint/services/importer.py
  custom_components/spook/ectoplasms/homeassistant/templating/flatten.py
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch.py
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch_filter.py
  custom_components/spook/ectoplasms/homeassistant/templating/shuffle.py
  poetry.lock
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: refactor

#692 Require at least Home Assistant 2024.4.0
  hacs.json
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: maintenance

#693 Clean up Poetry from Renovate configuration
  .github/renovate.json
Labels: maintenance

#694 Detect unknown labels used in automations
  custom_components/spook/ectoplasms/automation/repairs/unknown_label_references.py
  custom_components/spook/translations/en.json
  custom_components/spook/util.py
Labels: new-feature

#695 Detect unknown floors used in automations
  custom_components/spook/ectoplasms/automation/repairs/unknown_floor_references.py
  custom_components/spook/translations/en.json
  custom_components/spook/util.py
Labels: new-feature

#696 Detect unknown labels used in scripts
  custom_components/spook/ectoplasms/script/repairs/unknown_label_references.py
  custom_components/spook/translations/en.json
Labels: new-feature

#697 Detect unknown floors used in scripts
  custom_components/spook/ectoplasms/script/repairs/unknown_floor_references.py
  custom_components/spook/translations/en.json
Labels: new-feature

#699 Allow setting icon on homeassistant.create_area service
  custom_components/spook/ectoplasms/homeassistant/services/create_area.py
  custom_components/spook/services.yaml
Labels: new-feature

#702 Add homeassistant.create_floor service
  custom_components/spook/ectoplasms/homeassistant/services/create_floor.py
  custom_components/spook/services.yaml
Labels: new-feature

#703 Add homeassistant.add_alias_to_floor service
  custom_components/spook/ectoplasms/homeassistant/services/add_alias_to_floor.py
  custom_components/spook/services.yaml
Labels: new-feature

#704 Add homeassistant.remove_alias_from_floor service
  custom_components/spook/ectoplasms/homeassistant/services/remove_alias_from_floor.py
  custom_components/spook/services.yaml
Labels: new-feature

#705 Add homeassistant.set_floor_aliases service
  custom_components/spook/ectoplasms/homeassistant/services/set_floor_aliases.py
  custom_components/spook/services.yaml
Labels: new-feature

#706 Add homeassistant.add_area_to_floor service
  custom_components/spook/ectoplasms/homeassistant/services/add_area_to_floor.py
  custom_components/spook/services.yaml
Labels: new-feature

#707 Add homeassistant.remove_area_from_floor service
  custom_components/spook/ectoplasms/homeassistant/services/remove_area_from_floor.py
  custom_components/spook/services.yaml
Labels: new-feature

#708 Add homeassistant.delete_floor service
  custom_components/spook/ectoplasms/homeassistant/services/delete_floor.py
  custom_components/spook/services.yaml
Labels: new-feature
