Repository frenck/spook, pull requests merged in 2024-04, with the labels that each got.

#710 Fix gathering of all floor IDs
  custom_components/spook/util.py
Labels: bugfix

#711 Use floor selector in floor related services
  custom_components/spook/services.yaml
Labels: enhancement

#712 Add homeassistant.delete_label service
  custom_components/spook/ectoplasms/homeassistant/services/delete_label.py
  custom_components/spook/services.yaml
Labels: new-feature

#713 Add homeassistant.create_label service
  custom_components/spook/ectoplasms/homeassistant/services/create_label.py
  custom_components/spook/services.yaml
Labels: new-feature

#715 Add homeassistant.add_label_to_area service
  custom_components/spook/ectoplasms/homeassistant/services/add_label_to_area.py
  custom_components/spook/services.yaml
Labels: new-feature

#716 Add homeassistant.add_label_to_device service
  custom_components/spook/ectoplasms/homeassistant/services/add_label_to_device.py
  custom_components/spook/services.yaml
Labels: new-feature

#717 Add homeassistant.add_label_to_entity service
  custom_components/spook/ectoplasms/homeassistant/services/add_label_to_entity.py
  custom_components/spook/services.yaml
Labels: new-feature

#718 Add homeassistant.remove_label_from_area service
  custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_area.py
  custom_components/spook/services.yaml
Labels: new-feature

#719 Add homeassistant.remove_label_from_device service
  custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_device.py
  custom_components/spook/services.yaml
Labels: new-feature

#720 Add homeassistant.remove_label_from_entity service
  custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_entity.py
  custom_components/spook/services.yaml
Labels: new-feature

#721 Require at least Home Assistant 2024.4.0
  documentation/installation.md
  hacs.json
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: maintenance

#722 Fix blocking I/O on event loop while importing modules
  custom_components/spook/repairs.py
  custom_components/spook/services.py
  custom_components/spook/templating.py
  custom_components/spook/util.py
Labels: bugfix

#723 Move license to root of repo so GitHub picks it up
  LICENSE.md
Labels: maintenance

#724 Recommend Spook, instead of discourage the use
  documentation/index.md
Labels: documentation

#727 Update recorder.md to improve YAML example.
  documentation/integrations/recorder.md
Labels: documentation

#732 Fix area and floor registry service calls
  custom_components/spook/ectoplasms/homeassistant/services/add_alias_to_floor.py
  custom_components/spook/ectoplasms/homeassistant/services/remove_label_from_area.py
Labels: bugfix

#731 Misc typing improvements
  custom_components/spook/__init__.py
  custom_components/spook/config_flow.py
  custom_components/spook/ectoplasms/homeassistant/entity.py
  custom_components/spook/ectoplasms/homeassistant/templating/flatten.py
  custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py
  custom_components/spook/ectoplasms/recorder/services/import_statistics.py
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/ectoplasms/repairs/entity.py
  custom_components/spook/ectoplasms/repairs/event.py
  custom_components/spook/ectoplasms/timer/services/set_duration.py
  custom_components/spook/ectoplasms/zone/services/delete.py
  custom_components/spook/ectoplasms/zone/services/update.py
  custom_components/spook/integrations/spook_inverse/entity.py
  custom_components/spook/repairs.py
  custom_components/spook/services.py
  custom_components/spook/templating.py
  custom_components/spook/util.py
Labels: refactor

#733 Add EventType annotations
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/repairs.py
Labels: refactor

#730 Change Description dataclasses to frozen
  custom_components/spook/ectoplasms/cloud/entity.py
  custom_components/spook/ectoplasms/cloud/switch.py
  custom_components/spook/ectoplasms/homeassistant/button.py
  custom_components/spook/ectoplasms/homeassistant/sensor.py
  custom_components/spook/ectoplasms/repairs/button.py
  custom_components/spook/ectoplasms/repairs/event.py
  custom_components/spook/ectoplasms/repairs/sensor.py
Labels: enhancement

#682 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/de.json
  custom_components/spook/translations/el.json
  custom_components/spook/translations/es.json
  custom_components/spook/translations/fr.json
  custom_components/spook/translations/gl.json
  custom_components/spook/translations/he.json
  custom_components/spook/translations/hr.json
  custom_components/spook/translations/id.json
  custom_components/spook/translations/it.json
  custom_components/spook/translations/ja.json
  custom_components/spook/translations/nl.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/pt.json
  custom_components/spook/translations/sk.json
  custom_components/spook/translations/th.json
  custom_components/spook/translations/tr.json
  custom_components/spook/translations/zh_Hans.json
  custom_components/spook/translations/zh_Hant.json
Labels: maintenance

#685 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/cs.json
  custom_components/spook/integrations/spook_inverse/translations/el.json
  custom_components/spook/integrations/spook_inverse/translations/fr.json
  custom_components/spook/integrations/spook_inverse/translations/hr.json
  custom_components/spook/integrations/spook_inverse/translations/id.json
  custom_components/spook/integrations/spook_inverse/translations/nl.json
Labels: maintenance

#746 Fix frozen dataclass inherits from a non-frozen one
  custom_components/spook/entity.py
Labels: bugfix
