Repository frenck/spook, pull requests merged in 2025-03, with the labels that each got.

#910 Translations update from Hosted Weblate
  custom_components/spook/translations/cs.json
  custom_components/spook/translations/el.json
  custom_components/spook/translations/hu.json
  custom_components/spook/translations/id.json
  custom_components/spook/translations/it.json
  custom_components/spook/translations/nb_NO.json
  custom_components/spook/translations/pl.json
  custom_components/spook/translations/pt-BR.json
  custom_components/spook/translations/pt.json
  custom_components/spook/translations/sk.json
Labels: maintenance

#911 Remove old HACS install instructions
  documentation/images/installation/hacs_download.png
  documentation/images/installation/hacs_download_fab.png
  documentation/images/installation/hacs_find_spook.png
  documentation/images/installation/hacs_integrations.png
  documentation/installation.md
Labels: documentation

#913 Migrate pre-commit configuration
  .pre-commit-config.yaml
Labels: maintenance

#915 :fireworks: Updates maintenance/license year to 2025
  LICENSE.md
  README.md
  documentation/license.md
Labels: maintenance

#928 Translations update from Hosted Weblate
  custom_components/spook/translations/ru.json
  custom_components/spook/translations/sv.json
Labels: maintenance

#929 Translations update from Hosted Weblate
  custom_components/spook/integrations/spook_inverse/translations/ko.json
  custom_components/spook/integrations/spook_inverse/translations/sv.json
Labels: maintenance

#932 Translations update from Hosted Weblate
  custom_components/spook/translations/it.json
Labels: maintenance

#935 Remove template extensions
  custom_components/spook/__init__.py
  custom_components/spook/ectoplasms/homeassistant/templating/__init__.py
  custom_components/spook/ectoplasms/homeassistant/templating/flatten.py
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch.py
  custom_components/spook/ectoplasms/homeassistant/templating/fnmatch_filter.py
  custom_components/spook/ectoplasms/homeassistant/templating/md5.py
  custom_components/spook/ectoplasms/homeassistant/templating/sha1.py
  custom_components/spook/ectoplasms/homeassistant/templating/sha256.py
  custom_components/spook/ectoplasms/homeassistant/templating/sha512.py
  custom_components/spook/ectoplasms/homeassistant/templating/shuffle.py
  custom_components/spook/ectoplasms/homeassistant/templating/typeof.py
  custom_components/spook/templating.py
  custom_components/spook/util.py
  documentation/_toc.yml
  documentation/about.md
  documentation/core_extensions.md
  documentation/previous_features.md
  documentation/template_engine.md
  documentation/template_functions.md
  documentation/template_functions/flatten.md
  documentation/template_functions/fnmatch.md
  documentation/template_functions/fnmatch_filter.md
  documentation/template_functions/md5.md
  documentation/template_functions/sha1.md
  documentation/template_functions/sha256.md
  documentation/template_functions/sha512.md
  documentation/template_functions/shuffle.md
  documentation/template_functions/typeof.md
Labels: breaking-change
